project:
  type: website
  output-dir: docs

website:
  title: "huhhuhman의 블로그"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://linkedin.com
      - icon: github
        text: Github
        href: https://github.com
      - icon: blog
        text: blog
        href: https://velog.io/@stts1373/posts
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



